### ISSUE TITLE
Заменить "Оплаченный" на "Платный"

### ISSUE THREAD

**Issue by artemious7** [dotnet/EntityFramework.Docs.ru-ru#18]
В таблице поставщиков в колонке "Примечания и требования" предлагаю заменить "Оплаченный" на "Платный" (англ. "Paid")

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: c9338b2a-93b1-595a-2e8e-86119e6eecbd
* Version Independent ID: 9890ab79-bc72-6075-4294-5450e6693668
* Content: [Поставщики базы данных — EF Core](https://docs.microsoft.com/ru-ru/ef/core/providers/index?tabs=dotnet-core-cli#feedback)
* Content Source: [entity-framework/core/providers/index.md](https://github.com/aspnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/providers/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @artemious7
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by sampathkumarakula** [comment]
.

**Comment by CeciAc** [comment]
Здравствуйте, @artemious7 

Спасибо за отзыв.  

Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/ef/core/providers/index?tabs=dotnet-core-cli#feedback

Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы.  

С наилучшими пожеланиями,  

Международная команда поддержки документации Майкрософт

**Comment by srvbpigh** [comment]
Hello, @artemious7,  

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/ef/core/providers/index?tabs=dotnet-core-cli#feedback.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
