### ISSUE TITLE
Failed to mention 6.4

### ISSUE THREAD

**Issue by leotsarev** [dotnet/EntityFramework.Docs.ru-ru#19]
Please add 6.4 to this page

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: b2ea260e-f0da-5325-c8ab-75d8bf154c47
* Version Independent ID: c722e037-ae0a-7c78-09cc-d85a2569b427
* Content: [Новые возможности EF6](https://docs.microsoft.com/ru-ru/ef/ef6/what-is-new/)
* Content Source: [entity-framework/ef6/what-is-new/index.md](https://github.com/dotnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/ef6/what-is-new/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @leotsarev
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by leotsarev** [comment]
Opened PR to english version https://github.com/dotnet/EntityFramework.Docs/pull/2209

**Comment by CeciAc** [comment]
Hello, @leotsarev 
Thank you for your feedback and suggestion.  

The file is currently under localization process. We will release this article soon.
Many thanks for your support. 

 

Kind regards,

 

Microsoft DOCS Global Experience Team
