### ISSUE TITLE
Incorrect localization

### ISSUE THREAD

**Issue by churanovaleksey** [dotnet/EntityFramework.Docs.ru-ru#20]
Change Мигратионбуилдер to MigrationBuilder and Мигратионоператион to MigrationOperation

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: c13eb107-79c2-7824-12c1-e637d2a92add
* Version Independent ID: aafc9673-c635-3cf2-6235-8577ff15d19c
* Content: [Операции с настраиваемыми миграциями — EF Core](https://docs.microsoft.com/ru-ru/ef/core/managing-schemas/migrations/operations#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/operations.md](https://github.com/dotnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/managing-schemas/migrations/operations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by srvbpigh** [comment]
Hello, @churanovaleksey
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @churanovaleksey 

Thank you for your contribution. 

Contributions on translation problems against machine translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
