### ISSUE TITLE
Don`t translate this

### ISSUE THREAD

**Issue by zznobzz** [dotnet/EntityFramework.Docs.ru-ru#23]
ренамеколумн,  ренамеиндекс, дроппримарикэй  и т.д. - чуть кровь из глаз не пошла, поправьте.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: dbc4d900-28a8-9c04-2443-7407f15a684f
* Version Independent ID: 545bb0b5-f15b-584e-cef7-7283a0e0729f
* Content: [Поставщик базы данных SQLite — ограничения — EF Core](https://docs.microsoft.com/ru-ru/ef/core/providers/sqlite/limitations#feedback)
* Content Source: [entity-framework/core/providers/sqlite/limitations.md](https://github.com/dotnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/providers/sqlite/limitations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @zznobzz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @zznobzz 

Спасибо за Ваше предложение! 
 
Публикации о проблемах с содержимым, обработанным с помощью машинного перевода, сейчас не принимаются. 

Мы ценим ваши отзывы и предложения, касающиеся переведенного вручную содержимого. Мы используем их для обучения подсистем машинного перевода. Со временем это позволит улучшить качество как машинного, так и ручного перевода. 

Статьи, переведенные вручную, можно отличить от статей, обработанных с помощью машинного перевода, по значению метаданных ms.translationtype, которое равно "HT" (при использовании машинного перевода — "MT") в заголовке каждого файла с содержимым. 

Большое спасибо за поддержку! 

Microsoft DOCS Global Experience Team

**Comment by JasonCard** [comment]
Hi @zznobzz, 
Thank you for your feedback.
It's difficult for Machine Translation to not over-localize certain terms, so I've requested the writing team for help to block these terms from localization ([#2306](https://github.com/dotnet/EntityFramework.Docs/issues/2306)).

Best regards,
Jason
