### ISSUE TITLE
Перевод

### ISSUE THREAD

**Issue by Flow013** [dotnet/EntityFramework.Docs.ru-ru#24]
имоделкачекэйфактори

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 47e9155e-a702-17a1-848c-09a7d9a52bb5
* Version Independent ID: 23d9d8f5-b309-3a1e-cf3e-428d1edc0fdf
* Content: [Чередование между несколькими моделями с одинаковым типом DbContext — EF Core](https://docs.microsoft.com/ru-ru/ef/core/modeling/dynamic-model#feedback)
* Content Source: [entity-framework/core/modeling/dynamic-model.md](https://github.com/dotnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/modeling/dynamic-model.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @Flow013
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @Flow013 

Благодарим Вас за предоставленный комментарий. Комментарии помогают нам постоянно улучшать портал docs.microsoft.com. Однако нам необходимы дополнительные сведения, чтобы проанализировать Ваш отзыв. Не могли бы Вы дать более подробную информацию и пояснить свой комментарий? 

С уважением, 

Международная команда Microsoft DOCS

**Comment by AndriySvyryd** [comment]
The issue is with the second header - "имоделкачекэйфактори", it shouldn't be "translated" - IModelCacheKeyFactory

**Comment by CeciAc** [comment]
Здравствуйте, @Flow013 

Спасибо за Ваше предложение! 

Публикации о проблемах с содержимым, обработанным с помощью машинного перевода, сейчас не принимаются. 

Мы ценим ваши отзывы и предложения, касающиеся переведенного вручную содержимого. Мы используем их для обучения подсистем машинного перевода. Со временем это позволит улучшить качество как машинного, так и ручного перевода. 

Статьи, переведенные вручную, можно отличить от статей, обработанных с помощью машинного перевода, по значению метаданных ms.translationtype, которое равно "HT" (при использовании машинного перевода — "MT") в заголовке каждого файла с содержимым. 

Большое спасибо за поддержку! 

Microsoft DOCS Global Experience Team
