### ISSUE TITLE
Очепятка

### ISSUE THREAD

**Issue by fzakharov** [dotnet/EntityFramework.Docs.ru-ru#25]
&gt; Предотвращение проблем с многопоточной обDbContextкой

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a47bf610-692d-9d40-d85f-aec1e2a87a07
* Version Independent ID: 3c94634a-4b17-bc13-7436-0c61aea03ab6
* Content: [Настройка DbContext-EF Core](https://docs.microsoft.com/ru-ru/ef/core/miscellaneous/configuring-dbcontext#avoiding-dbcontext-threading-issues)
* Content Source: [entity-framework/core/miscellaneous/configuring-dbcontext.md](https://github.com/dotnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/miscellaneous/configuring-dbcontext.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @fzakharov
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Здравствуйте, @fzakharov ! 

Благодарим Вас за предоставленный комментарий. Комментарии помогают нам постоянно улучшать портал docs.microsoft.com. Однако нам необходимы дополнительные сведения, чтобы проанализировать Ваш отзыв. Не могли бы Вы дать более подробную информацию и пояснить свой комментарий? 

С уважением, 

Международная команда Microsoft DOCS

**Comment by CeciAc** [comment]
Здравствуйте, @fzakharov !

Еще раз благодарим Вас за предоставленный комментарий. 

К сожалению, у нас по-прежнему недостаточно данных для обработки Вашего отзыва. Пока что мы закрываем этот вопрос на GitHub, но надеемся получать от Вас подробные отзывы в будущем. 

С уважением, 

Международная команда Microsoft DOCS
