### ISSUE TITLE
Расширения AsSplitQuery и AsSingleQuery

### ISSUE THREAD

**Issue by Vasya02091983** [dotnet/EntityFramework.Docs.ru-ru#27]
Подскажите, какой пакет подключить или где расположена их реализация у меня VS2019 их нету. Подключённые пакеты: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.Tools.

**Comment by Rick-Anderson** [comment]
English: 

Tell me which package to connect or where their implementation is located, I don't have VS2019. Included packages: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.Tools.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
